# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-28 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0002_auto_20171028_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ref.Subsidiary', verbose_name='Subsidiary'),
        ),
    ]
